/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Views;

import Controller.Chitet_hdModify;
import Controller.HoaDonModify;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.chi_tiet_hd;
import model.quanlyhoadon;

/**
 *
 * @author Admin
 */
public class FindBillBy_sdt extends javax.swing.JDialog {

    /**
     * Creates new form FindBillBy_sdt
     */
    private Hoadon home;
   
   Chitet_hdModify dao = new Chitet_hdModify();
    HoaDonModify a = new HoaDonModify();
    ArrayList<quanlyhoadon> hoadon=new ArrayList<>();
    ArrayList<chi_tiet_hd> sanphamct = new ArrayList<>();
    private DefaultTableModel ModelFind;
    private DefaultTableModel ModelSPCT;
    int selectedIndex;
    String sdt="";
    public FindBillBy_sdt(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Tìm kiếm hóa đơn bằng sđt");
        home=(Hoadon) parent;
      ModelFind=(DefaultTableModel) table_find.getModel();
      ModelSPCT=(DefaultTableModel) table_chitiet.getModel();
        //showTableHD_find();
        //showTableSPCT();
        showTableHD_find();
        showTableHD();
        showTableSPCT();
        showTableSPCT_themmoi();
        showTableHD_themmoi();
    }
    //hiển thị bảng hóa đơn khi tìm kiếm
  public void showTableHD_find(){
        ModelFind.setRowCount(0);
        for(quanlyhoadon hd: a.findbySDT(sdt)){
            Object dataRow[]=new Object[5];
            dataRow[0]=hd.getMahd();
            dataRow[1]=hd.getSdt();
            dataRow[2]=hd.getTennv();
            dataRow[3]=hd.getDate_Buy();
            dataRow[4]=hd.getThanhTien();
            ModelFind.addRow(dataRow);
            
        }
    }
  //show bảng hóa đơn rỗng
  public void showTableHD() {
        ModelFind.setRowCount(0);
       
        for (quanlyhoadon s : hoadon) {
            Object[] row = new Object[]{
                table_find.getRowCount() + 1, s.getMahd(), s.getSdt(), s.getTennv(), s.getDate_Buy(),s.getThanhTien()};
           ModelFind.addRow(row);
        }

    }
//hiển thị bảng chi tiết hóa đơn khi tìm kiếm hóa đơn
    public void showTableSPCT() {
        ModelSPCT.setRowCount(0);
       
        for (chi_tiet_hd s : sanphamct) {
            Object[] row = new Object[]{
                table_chitiet.getRowCount() + 1, s.getTen_sp(), s.getSo_luong(), s.getGiaban(), s.getGia()};
            ModelSPCT.addRow(row);
        }

    }
    //hiển thị bảng chi tiết hóa đơn khi bấm reset
    public void showTableSPCT_themmoi() {
        sanphamct.clear();
        showTableSPCT();
      
    }
    //hiển thị bảng hóa đơn khi bấm reset
    public void showTableHD_themmoi()
    {
        hoadon.clear();
        showTableHD();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSdt = new javax.swing.JTextField();
        jFind = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_find = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_chitiet = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Tìm kiếm hóa đơn");

        jLabel3.setText("Số điện thoại khách");

        jFind.setText("Tìm");
        jFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFindActionPerformed(evt);
            }
        });

        table_find.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "SDT khách", "Tên nhân viên", "Ngày tạo", "Thanh toán"
            }
        ));
        table_find.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_findMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_find);

        table_chitiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã sản phẩm", "Số lượng", "Gía bán", "Tổng"
            }
        ));
        jScrollPane2.setViewportView(table_chitiet);

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("HÓA ĐƠN");

        jLabel5.setText("CHI TIẾT HÓA ĐƠN");

        jButton2.setText("thoat");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252)
                .addComponent(jLabel5)
                .addGap(387, 387, 387))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFind)
                            .addComponent(jButton1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3)
                        .addGap(65, 65, 65)
                        .addComponent(jSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jFind)
                        .addGap(33, 33, 33)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// tìm 
    private void jFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFindActionPerformed
        // TODO add your handling code here:
        sdt=jSdt.getText();
        System.out.println(sdt);
        showTableHD_find();
        
    }//GEN-LAST:event_jFindActionPerformed
// click trong bảng hóa đơn
    private void table_findMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_findMouseClicked
        // TODO add your handling code here:
        int numRow = table_find.getSelectedRow();
        int ma_hd = Integer.parseInt(table_find.getValueAt(numRow, 0).toString());
        sanphamct = new Chitet_hdModify().getchi_tiet_hdByMa_hd(ma_hd);
        ModelSPCT.setRowCount(0);
        sanphamct.forEach((chi_tiet_hd) -> {
            ModelSPCT.addRow(new Object[]{table_chitiet.getRowCount() + 1, chi_tiet_hd.getTen_sp(), chi_tiet_hd.getSo_luong(), chi_tiet_hd.getGiaban(), chi_tiet_hd.getGia()});
        });
    }//GEN-LAST:event_table_findMouseClicked
// reset
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jSdt.setText("");
        showTableSPCT_themmoi();
        showTableHD_themmoi();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        Hoadon h= new Hoadon();
        h.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindBillBy_sdt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindBillBy_sdt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindBillBy_sdt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindBillBy_sdt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FindBillBy_sdt dialog = new FindBillBy_sdt(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jFind;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jSdt;
    private javax.swing.JTable table_chitiet;
    private javax.swing.JTable table_find;
    // End of variables declaration//GEN-END:variables

    
}
