/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Product;
import Controller.ProductModify;
import Controller.chitietnhaphangDAO;
import model.chitietnhaphang;
import model.nhanvien;
import model.nhaphang;
import Controller.nhaphangDAO;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import model.chi_tiet_hd;

/**
 *
 * @author trant
 */
public class test extends javax.swing.JFrame {
     
    chitietnhaphangDAO da= new chitietnhaphangDAO();
    ProductModify dao = new ProductModify();
    nhaphangDAO a= new nhaphangDAO();
    ProductModify p= new ProductModify();

    private List<nhaphang> nhap_hang;
    private List<Product> sanpham;
    //private List<chi_tiet_hd> sanphamct;
   ArrayList<chitietnhaphang> nhaphangct=new ArrayList<>();
    private DefaultTableModel modelnhap;
     
    private DefaultTableModel modelctnh;
    private DefaultTableModel ModelSPCT;
    int selectedIndex;
    /**
     * Creates new form test
     */
    public test() {
        initComponents();
        modelctnh=(DefaultTableModel) tablectnh.getModel();
        modelnhap= (DefaultTableModel) tablenhaphang.getModel();
        showTablenh();
        showTableSPCT();
        //ModelSPCT=(DefaultTableModel) table_chi_tiet_hd.getModel();
      
    }
    
    private void showTablenh(){
        
        nhap_hang=new nhaphangDAO().getListNH();
        modelnhap.setRowCount(0);
        for(nhaphang nh:nhap_hang){
            modelnhap.addRow(new Object[]{
                nh.getManhap(), nh.getMancc(), nh.getManv(), nh.getNgaynhap(), nh.getThanhtien()
            });
        }
         
    }
    
   public void showTableSPCT(){
       System.out.println(".....");
        modelctnh.setRowCount(0);
        //ArrayList<chi_tiet_hd> sanphamct=new ArrayList<>();
        for(chitietnhaphang s:nhaphangct)
        {
             
            Object[] row=new Object[]
            {  
                tablectnh.getRowCount()+1 ,s.getTenhang(),s.getGianhap(),s.getSoluong(),s.getTongtien()
            };
                modelctnh.addRow(row);
                  
            }
          
    }
      public void showTableSPCT_themmoi(){
        nhaphangct.clear();
        showTablenh();
        filldata();
    }
      public void filldata(){
           
         DefaultTableModel model2=(DefaultTableModel)tableNhapngay.getModel();
          model2.setRowCount(0);
        for(Product pr: dao.getProducts()){
           Object dataRow[]=new Object[3];
            dataRow[0]=pr.getMa_sp();
            dataRow[1]=pr.getTen_sp();

            dataRow[2]=pr.getSo_luong();
            model2.addRow(dataRow);
        }
    }
       public Product getModel(){
        Product pr=new Product();
     
        pr.setTen_sp(Jtenhang.getText());
       
        pr.setSo_luong(Integer.parseInt(Jsoluong.getText()));
        return pr;
    }
     /*
    public ArrayList getlinhtinh(){
        ArrayList<String> a = new ArrayList<>();

        // Add elements
        int k= Integer.parseInt(Jgianhap.getText())*Integer.parseInt(Jsoluong.getText());
        a.add(Jmancc.getText());
        a.add(Jtenhang.getText());
        a.add(Jsoluong.getText());
        a.add(Jgianhap.getText());
        a.add(k);
        a.add("Horse");
     //   System.out.println("ArrayList: " + animals);
        return a;
    }
       */
   
     
      
     public Product getModel_add(){
        Product pr=new Product();
        pr.setTen_sp(Jtenhang.getText());
       pr.setGia_ban(Integer.parseInt(Jgianhap.getText())+11);
        return pr;
    }
    public String getdate(){
     DateTimeFormatter dtf = DateTimeFormatter.ofPattern("uuuu/MM/dd HH:mm:ss");
    ZonedDateTime now = ZonedDateTime.now();
    String date= dtf.format(now);
    return date;
 }
    public void luu_hang(){
    for(int i=0;i<nhaphangct.size();i++)
    {
        Product pr= new Product(nhaphangct.get(i).getTenhang(),(nhaphangct.get(i).getGianhap()+2), nhaphangct.get(i).getSoluong());
        p.add(pr);
    }
}
    public void luu_db_chi_tiet_nh(int k){
    for(int i=0;i<nhaphangct.size();i++)
    {
        int masp= p.getmasp(nhaphangct.get(i).getTenhang());
        int sl= nhaphangct.get(i).getSoluong();
        int gianhap= nhaphangct.get(i).getGianhap();
        int tong=nhaphangct.get(i).getGianhap();
        chitietnhaphang sp=new chitietnhaphang(gianhap, sl, tong, masp);
       da.addnh(sp,k);
        System.out.println(sp);
    }    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablectnh = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        Jtenhang = new javax.swing.JTextField();
        Jsoluong = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Jgianhap = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Jmancc = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablenhaphang = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtongnhap = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableNhapngay = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton3.setText("thêm vào giỏ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("tên hàng");

        jLabel2.setText("số lượng");

        tablectnh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "stt", "tên hàng", "giá nhập", "số lượng", "tổng tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablectnh);

        jLabel3.setText("chi tiết nhập hàng");

        jButton1.setText("thanh toan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("giá nhập");

        jLabel5.setText("tổng tiền");

        jLabel8.setText("mã ncc");

        Jmancc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JmanccActionPerformed(evt);
            }
        });

        tablenhaphang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "mã nhập", "mã ncc", "mã nhân viên", "ngày nhập", "thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablenhaphang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablenhaphangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablenhaphang);

        jButton2.setText("thanh toán");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("chi tiết nhập hàng");

        jLabel7.setText("phiếu nhập hàng");

        jButton4.setText("thoát");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tableNhapngay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ma hang", "ten hang", "so luong"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableNhapngay);

        jLabel9.setText("hang sap het");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jButton3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jtongnhap))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel2))
                                            .addGap(109, 109, 109))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(119, 119, 119)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(Jtenhang, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                                .addComponent(Jsoluong)
                                                .addComponent(Jmancc)
                                                .addComponent(Jgianhap))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(jLabel3))
                            .addComponent(jLabel4))
                        .addGap(28, 28, 28)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(405, 405, 405))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(221, 221, 221))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(384, 384, 384))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Jmancc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Jtenhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(Jsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Jgianhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jtongnhap)))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton2)
                            .addComponent(jButton4)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 510, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        int soluong=0;
        int gia=0;  
        
        soluong=Integer.parseInt(Jsoluong.getText());
        gia=Integer.parseInt(Jgianhap.getText());
        int tong=soluong*gia;
        
        chitietnhaphang sp=new chitietnhaphang(gia,soluong,tong,Jtenhang.getText());
       nhaphangct.add(sp);
        //dao.addSP(sp);
       // dao.Dungtest(GIA);
       
       int tonggia=0;
        showTableSPCT();
         for(int i=0;i<tablectnh.getRowCount();i++)
       { 
            tonggia+=Integer.parseInt(tablectnh.getValueAt(i, 4).toString());
        }
       jtongnhap.setText(tonggia+"");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
               
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JmanccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JmanccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JmanccActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Login l= new Login();
        
  //thanh toán 
 
        String DateBuy=getdate();
        
        int tong=0;
        for(int i=0;i<tablectnh.getRowCount();i++)
        {
            tong+=Integer.parseInt(tablectnh.getValueAt(i, 4).toString());
        }
         System.out.println("hhihi");
        nhaphang nh= new nhaphang(Integer.parseInt(Jmancc.getText()),l.returnma(), DateBuy, Integer.parseInt(jtongnhap.getText()));
       System.out.println(nh);
        if(a.add(nh)>0){
            luu_hang();
            
            luu_db_chi_tiet_nh(a.getmanh(DateBuy));
         //   showTablenh();
         showTablenh();
             JOptionPane.showMessageDialog(this, "Them hoa don thanh cong-----!");
        }
 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tablenhaphangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablenhaphangMouseClicked
        // TODO add your handling code here:
         int numRow=tablenhaphang.getSelectedRow();
       int ma_nh=Integer.parseInt(tablenhaphang.getValueAt(numRow, 0).toString());   
        System.out.println(ma_nh);
        nhaphangct=new chitietnhaphangDAO().getchi_tiet_nhByMa_nh(ma_nh);
        ModelSPCT.setRowCount(0);
        nhaphangct.forEach((chi_tiet_hd)->{
            ModelSPCT.addRow(new Object[]{tablectnh.getRowCount()+1,chi_tiet_hd.getMa_hang(),chi_tiet_hd.getSoluong(),chi_tiet_hd.getGianhap(),chi_tiet_hd.getTongtien()});
        });
        
        showTableSPCT();
    }//GEN-LAST:event_tablenhaphangMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
       Sanpham ah = new  Sanpham();
       ah.show();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Jgianhap;
    private javax.swing.JTextField Jmancc;
    private javax.swing.JTextField Jsoluong;
    private javax.swing.JTextField Jtenhang;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel jtongnhap;
    private javax.swing.JTable tableNhapngay;
    private javax.swing.JTable tablectnh;
    private javax.swing.JTable tablenhaphang;
    // End of variables declaration//GEN-END:variables
}
